### PR TITLE
CMSPLT-36: Updating to use c3p0 connection pool

### PR DESCRIPTION
**Pull request by shawnconnolly**
https://issues.jasig.org/browse/CMSPLT-36
Pull request in uPortal complements this one:
https://github.com/Jasig/uPortal/pull/266

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
Hey @shawnconnolly, it looks like some merge conflicts have cropped up, could you resolve them?

**Comment by shawnconnolly** [comment]
Hi @ChristianMurphy, if I recall correctly the code from this pull request never was merged into the CMSPLT.
The following link has what became of that effort(closed with unmerged code).
[https://github.com/Jasig/uPortal/pull/266](https://github.com/Jasig/uPortal/pull/266)

It looks like the solution that was used in its stead was documented in [https://issues.jasig.org/browse/CMSPLT-36](https://issues.jasig.org/browse/CMSPLT-36) with two loose commits being merged.

You are definitely welcome to look at/use my branches, however I think they are outdated at this point(about 3 years old and about 100 commits behind).  You will want to use the Jasig version to start from:
[https://github.com/Jasig/SimpleContentPortlet](https://github.com/Jasig/SimpleContentPortlet).

I am no longer set up to easily work with/test this code, but if there is other info around this that is not clear/documented please let me know.

**Comment by ChristianMurphy** [comment]
Thanks for the update @shawnconnolly!

**Comment by bjagg** [comment]
Closing PR without merging per comments

**Pull request closed without merging**
